In [4]:
#numpy 사용하기
import numpy as np

In [7]:
data1 = [1,2,3,4,5]
data2 = [1,2,3,4,5,6]
print(data1)
print(data2)

[1, 2, 3, 4, 5]
[1, 2, 3, 4, 5, 6]


In [8]:
#numpy를 이용하여  array 정의하기

arr1 = np.array(data1)
arr1

array([1, 2, 3, 4, 5])

In [9]:
#array의 형태(크기)를 확인할 수 있다.
arr1.shape

(5,)

In [10]:
arr3 = np.array([1,2,3,4,5,6,78,9])
arr3

array([ 1,  2,  3,  4,  5,  6, 78,  9])

In [11]:
arr3.shape

(8,)

In [12]:
#자료형을 확인할 수 있다.
arr3.dtype

dtype('int32')

In [13]:
arr4 = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
arr4

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [15]:
arr4.shape
#(행, 열) 의 크기

(4, 3)

##  np.zeros / np.ones / np.arange

In [16]:
#np.zeros() 함수는 인자로 받는 크기만큼, 모든요소가 0인 array를 만든다.
print(np.zeros(10))
print(np.zeros((3,5)))

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [18]:
#np.ones() 함수는 인자로 받는 크기만큼, 모든요소가 1인 array를 만든다
print(np.ones(9))
print(np.ones((3,10)))

[1. 1. 1. 1. 1. 1. 1. 1. 1.]
[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


In [19]:
# np.aranges() 함수는 인자로 받는 값만큼 1씩 증가하는 1차원 array를 만든다
# 이때 하나의 인자만 입력하면 0~ 입력한 인자, 값만큼의 크기를 가진다

In [21]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [23]:
np.arange(3,10)

array([3, 4, 5, 6, 7, 8, 9])

In [24]:
np.arange(3,10).shape

(7,)

## array 연산
- array의 크기가 같은것끼리만 연산 가능하다

In [25]:
arr1 = np.array([[1,2,3],[4,5,6]])
arr1

array([[1, 2, 3],
       [4, 5, 6]])

In [26]:
arr1.shape

(2, 3)

In [27]:
arr2 = np.array([[10,11,12],[13,14,15]])
arr2

array([[10, 11, 12],
       [13, 14, 15]])

In [28]:
arr2.shape

(2, 3)

In [29]:
arr1 + arr2

array([[11, 13, 15],
       [17, 19, 21]])

In [30]:
arr1 - arr2

array([[-9, -9, -9],
       [-9, -9, -9]])

In [32]:
arr1 * arr2
######
# 행렬의 곱처럼 진행되는것이 아니라 요소별로 곱셈이 진행된다

array([[10, 22, 36],
       [52, 70, 90]])

In [33]:
arr1 / arr2

array([[0.1       , 0.18181818, 0.25      ],
       [0.30769231, 0.35714286, 0.4       ]])

# array의 브로드 캐스트
- 위에서는 array가 같은 크기를 가져야 서로 연산이 가능하다고 했지만,
    numpy에서는 브로드캐스트라는 기능을 제공한다.
    브로드캐스트란, 서로크기가 다른 array가 연산이 가능하게끔 하는것

In [34]:
arr1

array([[1, 2, 3],
       [4, 5, 6]])

In [35]:
arr1.shape

(2, 3)

In [36]:
arr3 =np.array([10,11,12])
arr3

array([10, 11, 12])

In [37]:
arr3.shape

(3,)

In [38]:
arr1 + arr3

array([[11, 13, 15],
       [14, 16, 18]])

In [39]:
arr1 * arr3

array([[10, 22, 36],
       [40, 55, 72]])

위와 같이 서로 크기가 다른 arr1과 arr3의 연산이 가능하다
연산결과를 살펴보면 ar3이 [10,11,12] 에서 [[10,11,12],[10,11,12]] 로 확장되어 계산되었음을 확인할 수 있다.
동일한 방식으로 하나의 array에 스칼라 연산도 가능하다.

In [43]:
arr1 * 10
#스칼라 연산도 가능하다

array([[10, 20, 30],
       [40, 50, 60]])

In [45]:
#요소에 제곱 처리
arr1 ** 2
#dtype이 왜 나오지?

array([[ 1,  4,  9],
       [16, 25, 36]], dtype=int32)

In [47]:
whos

Variable   Type       Data/Info
-------------------------------
a          ndarray    3: 3 elems, type `int32`, 12 bytes
arr1       ndarray    2x3: 6 elems, type `int32`, 24 bytes
arr2       ndarray    2x3: 6 elems, type `int32`, 24 bytes
arr3       ndarray    3: 3 elems, type `int32`, 12 bytes
arr4       ndarray    4x3: 12 elems, type `int32`, 48 bytes
data1      list       n=5
data2      list       n=6
np         module     <module 'numpy' from 'C:\<...>ges\\numpy\\__init__.py'>


# Array 인덱싱
- numpy에서 사용되는 인덱싱은 기본적으로 python 인덱싱과 동일하다.
    이때, python에서와 같이 1번째로 시작하는것이 아니라 0번째로 시작하는것에 주의한다

In [48]:
arr1 = np.arange(10)
arr1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [49]:
# 0 번째 요소
arr1[0]

0

In [50]:
arr1[3]

3

In [51]:
arr1[3:9]

array([3, 4, 5, 6, 7, 8])

In [52]:
arr1[:]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [54]:
arr2 = np.array([[1,2,3,4],
                [5,6,7,8],
               [9,10,11,12]])
arr2

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

# 2차원 array에서는 인덱싱하려면 2개의 인자를 받아야 한다

In [55]:
arr2.shape

(3, 4)

In [56]:
arr2[0,0]

1

In [59]:
arr2[2,3]

12

In [60]:
arr2[:,3]

array([ 4,  8, 12])

In [61]:
arr2[2,:]

array([ 9, 10, 11, 12])

# array boolean 인덱싱(마스크)
- 위에서 이용한 다차원의 인덱싱을 응용하여 boolean인덱싱을 할 수 있다.
    해당기능은 주로 마스크라고 이야기하는데, boolean인덱싱을 통해 만들어낸 array를 통해 우리가 원하는 행 또는 열의 값만 뽑아낼 수 있다.
    즉, 마스크처럼 우리가 가리고 싶은 부분은 가리고, 원하는 요소만 꺼낼 수 있다.

In [62]:
names = np.array(['Beomwoo','Beomwoo','Kim','Joan','Lee','Beomwoo','Park','Beomwoo'])
names

array(['Beomwoo', 'Beomwoo', 'Kim', 'Joan', 'Lee', 'Beomwoo', 'Park',
       'Beomwoo'], dtype='<U7')

In [64]:
names.shape

(8,)

In [91]:
#아래에서 사용되는 np.random.randn() 함수는 기대값이 0이고, 
#표준편차가 1인 가우시안 정규 분포를 따르는 난수를 발생시키는 함수이다
# 이 외에도 0~1의 난수를 발생시키는 np.random.rand() 함수도 존재한다.
data = np.random.randn(8,4)
data

array([[ 0.88392789,  1.41397265,  1.44205223,  0.51142873],
       [-0.90697671, -1.22273583, -2.12696125, -0.27767401],
       [ 1.20063652,  0.95366119, -0.92323177, -0.56532973],
       [ 0.68192142,  0.90780528, -1.01228802, -0.1814025 ],
       [-0.1050089 , -0.04547525,  0.331943  ,  1.26895284],
       [-0.16853936, -2.68279089,  1.63352919, -2.73325807],
       [-1.24746651,  1.28278004, -0.39207502, -0.30063545],
       [-1.00482791,  0.21297227, -0.98071961, -1.09140181]])

In [92]:
data.shape

(8, 4)

- 위와 같은 names와 data라는 array가 있다.
    이때, names의 각 요소가 data의 각 행과 연결된다고 가정해보자.
    그리고 이 때, names가 Beomwoo인 행의 data만 보고 싶을 때 다음과 같이 마스크를 사용한다.

In [93]:
# 요소가 Beowoo인 항목에 대한 mask 생성
names_Beomwoo_mask = (names == "Beomwoo")
names_Beomwoo_mask

array([ True,  True, False, False, False,  True, False,  True])

In [94]:
 data[names_Beomwoo_mask,:]

array([[ 0.88392789,  1.41397265,  1.44205223,  0.51142873],
       [-0.90697671, -1.22273583, -2.12696125, -0.27767401],
       [-0.16853936, -2.68279089,  1.63352919, -2.73325807],
       [-1.00482791,  0.21297227, -0.98071961, -1.09140181]])

In [95]:
# 요소가 kim인 행의 데이터만 꺼내기
data[names == 'Kim' , :]

array([[ 1.20063652,  0.95366119, -0.92323177, -0.56532973]])

In [96]:
#논리 연산을 응용하여, 요소가 kim 또는 Park인 행의 데이터만 꺼내기
data[(names == 'Kim') | (names == 'Park'), :]

array([[ 1.20063652,  0.95366119, -0.92323177, -0.56532973],
       [-1.24746651,  1.28278004, -0.39207502, -0.30063545]])

- 물론 data array 자체적으로도 마스크를 만들고, 이를 응용하여 인덱싱이 가능하다.
    data array에서 0번째 열의 값이 0보다 작은 행을 구해보자.

In [97]:
# 먼저 마스크를 만든다.
# data array에서 0번쨰 열이 0보다 작은 요소의 boolean값은 다음과 같다
data[:,0]< 0 

array([False,  True, False, False,  True,  True,  True,  True])

In [98]:
 #위에서 만든 마스크를 이용하여 0번째 열의 값이 0보다 작은 행을 구한다.
data[data[:,0]<0,:]

array([[-0.90697671, -1.22273583, -2.12696125, -0.27767401],
       [-0.1050089 , -0.04547525,  0.331943  ,  1.26895284],
       [-0.16853936, -2.68279089,  1.63352919, -2.73325807],
       [-1.24746651,  1.28278004, -0.39207502, -0.30063545],
       [-1.00482791,  0.21297227, -0.98071961, -1.09140181]])

- 이를 통해 특정 위치에만 우리가 원하는 값을 대입할 수 있다.
    위에서 얻은, 0번째 열의 값이 0보다 작은 행의 2,3번째 열값에 0을 대입해보자

In [103]:
#0번째 열의 값이 0보다 작은 행의 2,3번째 열 값
data[data[:,0]<0,2:4]

array([[-2.12696125, -0.27767401],
       [ 0.331943  ,  1.26895284],
       [ 1.63352919, -2.73325807],
       [-0.39207502, -0.30063545],
       [-0.98071961, -1.09140181]])

In [104]:
data[data[:,0]<0,2:4] = 0
data

array([[ 0.88392789,  1.41397265,  1.44205223,  0.51142873],
       [-0.90697671, -1.22273583,  0.        ,  0.        ],
       [ 1.20063652,  0.95366119, -0.92323177, -0.56532973],
       [ 0.68192142,  0.90780528, -1.01228802, -0.1814025 ],
       [-0.1050089 , -0.04547525,  0.        ,  0.        ],
       [-0.16853936, -2.68279089,  0.        ,  0.        ],
       [-1.24746651,  1.28278004,  0.        ,  0.        ],
       [-1.00482791,  0.21297227,  0.        ,  0.        ]])

# numpy 함수
- numpy에서는 array에 적용되는 다양한 함수가 있다.

#### 6-1. 하나의 array에 적용되는 함수

In [105]:
arr1 = np.random.randn(5,3)
arr1

array([[ 0.59861343, -1.48780903, -0.90660317],
       [ 1.00930746,  0.18775447, -0.80391581],
       [-0.88119286,  0.01164906, -0.11044689],
       [ 0.56220431, -0.94525638, -1.15916966],
       [ 0.24033191,  0.82007932,  1.90550126]])

In [106]:
#각 성분의 절대값 계산하기
np.abs(arr1)

array([[0.59861343, 1.48780903, 0.90660317],
       [1.00930746, 0.18775447, 0.80391581],
       [0.88119286, 0.01164906, 0.11044689],
       [0.56220431, 0.94525638, 1.15916966],
       [0.24033191, 0.82007932, 1.90550126]])

In [107]:
# 각 성분의 제곱근 계산하기 (== array ** 0,5)
np.sqrt(arr1)

<ipython-input-107-8d50df4812da>:2: RuntimeWarning: invalid value encountered in sqrt
  np.sqrt(arr1)


array([[0.77370113,        nan,        nan],
       [1.00464295, 0.43330644,        nan],
       [       nan, 0.10793079,        nan],
       [0.74980285,        nan,        nan],
       [0.49023658, 0.90558231, 1.38039895]])

In [108]:
# 각 성분의 제곱 계산하기
np.square(arr1)

array([[3.58338044e-01, 2.21357572e+00, 8.21929304e-01],
       [1.01870154e+00, 3.52517424e-02, 6.46280637e-01],
       [7.76500853e-01, 1.35700503e-04, 1.21985145e-02],
       [3.16073692e-01, 8.93509629e-01, 1.34367430e+00],
       [5.77594248e-02, 6.72530089e-01, 3.63093507e+00]])

In [109]:
#각 성분을 무리수e의 지수로 삼을 값을 계산하기
np.exp(arr1)


array([[1.81959406, 0.22586698, 0.40389386],
       [2.74370023, 1.20653724, 0.44757292],
       [0.41428843, 1.01171717, 0.89543389],
       [1.75453579, 0.38857993, 0.31374659],
       [1.27167115, 2.27067994, 6.72277667]])