수학한 사과의 총 개수를 출력합니다.

N x N의 격자판
첫줄에 자연수 N(홀수)가 주어진다 (3 <= N <= 20 )
두번째 줄부터 N줄에 걸쳐 각 줄에 N개의 자연수가 주어진다.
이 자연수는 각 격자안에 있는 사과나무에 열린 사과의 개수이다.
각 격자안의 사과의 개수는 100을 넘지않는다'



인덱스 문제를 풀때는 항상 주변에 노트로 적으면서 풀어보자

In [29]:
f=open('사과나무in1.txt',"r")
n = int(f.readline())
a = [list(map(int,f.readline().split())) for _ in range(n)] 
# map 함수가 가장 빠르다
# _ 를 왜 쓰나? index 쓸일이 없으니 그냥 range(n) 만큼만 회전시킨다

피클로 저장????

- 저장하고 읽어들일때 집합 튜플 리스트 같은 정보를 기억하기 위해
- 이럴때 피클을 

In [30]:
a

[[74, 10, 31, 26, 59, 16, 89],
 [78, 44, 49, 1, 64, 33, 15],
 [9, 95, 70, 18, 22, 25, 40],
 [62, 77, 28, 3, 78, 75, 23],
 [82, 38, 20, 16, 42, 1, 79],
 [1, 24, 2, 25, 95, 26, 79],
 [4, 35, 46, 94, 70, 44, 83]]

In [47]:
result = 0
mid = int(n/2)
for i in range(n):
    if i == 0 or n-1:
        result += a[i][mid]

print(result)

183


In [43]:
a[0][1:4]

[10, 31, 26]

# index 문제가 왜 안풀리는지 고민해보자 ㅠㅠ

In [57]:
def N_Matrix(n):
    import random
    random.seed(0) # 랜덤시드는 시드를 맞추면 맞춘 시드끼리는 램덤으로 주어져도 값을 같게 맞출수있다
    return [[random.randint(1,n*n) for i in range(n)] for j in range(n)]

In [58]:
x = 3
m1 = N_Matrix(x)
for i in range(x):
    print(m1[i])

[7, 7, 1]
[5, 9, 8]
[7, 5, 8]


# 선생님 풀이

In [62]:
f=open('사과나무in1.txt',"r")
n = int(f.readline())
a = [list(map(int,f.readline().split())) for _ in range(n)] 

sum = 0
s=e=n//2 # 몫을 구하는거라 정수만 취한다
# 시작은 s index이고 마지막은 e index 이다

for i in range(n):
    for j in range(s,e+1):
        sum = sum + a[i][j]
    if i < n//2 : 
        s= s -1 ; e= e+1
    else:
        s= s+1 ; e= e-1

print(sum)
f.close()

1049


In [65]:
# 사과나무 in 2 도 해보자
# with 사용

In [64]:
with open('사과나무in2.txt',"r") as f:
    n = int(f.readline())
    a = [list(map(int,f.readline().split())) for _ in range(n)] 

    sum = 0
    s=e=n//2 # 몫을 구하는거라 정수만 취한다
    # 시작은 s index이고 마지막은 e index 이다

    for i in range(n):
        for j in range(s,e+1):
            sum = sum + a[i][j]
        if i < n//2 : 
            s= s -1 ; e= e+1
        else:
            s= s+1 ; e= e-1

    print(sum)

1991


대표적인 index 문제로 마방진을 구하는 문제가 있다


- 4 9 2
- 3 5 7
- 8 1 6

어느방향의 가로세로를 더해도 15가 나온다

N*N Matrix 마방진을 만들어보세요..
1. N은 홀수로 입력 받는다. N은 3이상이다.
2. 가로세로대각선의 합이 같은 매트릭스를 만드세요

In [67]:
# 마방진~ 일단 3x3

def Matrix(N):
    M =  for i in range(n) for j in range(n)

SyntaxError: invalid syntax (<ipython-input-67-4e248f929b63>, line 4)

# 선생님 풀이

In [74]:
import numpy as np
n=int(input("n*n 마방진을 위한 n값을 입력(3이상, 홀수만)"))
matrix = np.zeros((n,n), dtype=int)

s_row=0; s_col=n//2
matrix[s_row, s_col] = 1
row = 0; col = 0

for i in range(2, n*n+1):
    row = s_row # 전 위치값  row 값 보관
    col = s_col # 전 위치값 col 값 보관
    
    s_row = s_row -1 ; s_col = s_col + 1
    
    if s_row < 0 :
        s_row = n -1
    if s_col > n-1 :
        s_col = 0
    
    if matrix[s_row, s_col] == 0:
        matrix[s_row, s_col] = i
    else: #0이 아니면 다른 숫자가 있다는 얘기
        s_row = row + 1 ; s_col = col
        matrix[s_row, s_col] = i
print(matrix)

n*n 마방진을 위한 n값을 입력(3이상, 홀수만)17
[[155 174 193 212 231 250 269 288   1  20  39  58  77  96 115 134 153]
 [173 192 211 230 249 268 287  17  19  38  57  76  95 114 133 152 154]
 [191 210 229 248 267 286  16  18  37  56  75  94 113 132 151 170 172]
 [209 228 247 266 285  15  34  36  55  74  93 112 131 150 169 171 190]
 [227 246 265 284  14  33  35  54  73  92 111 130 149 168 187 189 208]
 [245 264 283  13  32  51  53  72  91 110 129 148 167 186 188 207 226]
 [263 282  12  31  50  52  71  90 109 128 147 166 185 204 206 225 244]
 [281  11  30  49  68  70  89 108 127 146 165 184 203 205 224 243 262]
 [ 10  29  48  67  69  88 107 126 145 164 183 202 221 223 242 261 280]
 [ 28  47  66  85  87 106 125 144 163 182 201 220 222 241 260 279   9]
 [ 46  65  84  86 105 124 143 162 181 200 219 238 240 259 278   8  27]
 [ 64  83 102 104 123 142 161 180 199 218 237 239 258 277   7  26  45]
 [ 82 101 103 122 141 160 179 198 217 236 255 257 276   6  25  44  63]
 [100 119 121 140 159 178 197 216 235 254 256 

아 존나 어려워 ㅠㅠ
일단 외워보자...안되도 정말 외워서 머리에 넣어보자

In [83]:

a = range(10,1,-1)

In [84]:
list(a)

[10, 9, 8, 7, 6, 5, 4, 3, 2]