In [1]:
import numpy as np
from scipy import stats       # 통계에 관한 라이브러리(왠만한건 다 있다)


In [2]:
np.random.seed(0)

In [16]:
np.random.seed(0)
data=np.random.randint(0,100, 10000)
mean = np.mean(data) ; print('평균=', mean.round(2))
median = np.median(data) ; print('중앙값=', median)

# stats.mode(data)
print('최빈값=', stats.mode(data).mode[0])
print('최빈값의 출현한 횟수는=', stats.mode(data).count[0])

평균= 49.17
중앙값= 49.0
최빈값= 3
최빈값의 출현한 횟수는= 125


In [13]:
a, b = stats.mode(data)

In [14]:
a , b

(array([3]), array([125]))

In [17]:
# mode라는 말이 나오면 그것은 최빈값이다

In [18]:
temp= [7,7,7,7,7,8,2,5,1,6,4,8,4,9]

In [20]:
mean = np.mean(temp) ; print('평균=', mean.round(2))
median = np.median(temp) ; print('중앙값=', median)

# stats.mode(temp)
print('최빈값=', stats.mode(temp).mode[0])
print('최빈값의 출현한 횟수는=', stats.mode(temp).count[0])

평균= 5.86
중앙값= 7.0
최빈값= 7
최빈값의 출현한 횟수는= 5


In [21]:
a= np.array([[1,2,3,4,5,6,7,8,9,10]])

In [22]:
a

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10]])

In [23]:
np.percentile(a,0)

1.0

In [24]:
np.percentile(a,25) # a에서 25%에 해당하는 정도

3.25

In [25]:
a = np.array(a)

In [27]:
np.percentile(a,0)

1.0

In [28]:
np.percentile(a,25)

3.25

In [29]:
import random
a = [random.randint(1,51) for xx in range(1,101)]

In [30]:
a = np.array(a)

In [31]:
a

array([23, 37, 28,  3, 17, 50, 23, 25,  2, 32, 30, 26, 30,  4,  6, 10, 27,
       17, 41, 45, 18, 27, 42, 21, 47, 17,  9, 33, 25, 51, 41, 10, 33, 39,
       36, 45, 44, 42, 47,  4, 30, 50, 22, 26, 48, 28, 49, 24,  6, 44, 22,
       28, 22, 11, 10, 25, 16, 33, 10, 18, 33, 14, 40, 10, 19, 38, 44, 39,
       48, 13, 21, 48, 11, 15, 23,  8, 50, 39, 51, 16,  6, 33,  7,  1, 28,
       26,  3,  3, 25, 47, 21, 30, 26, 48, 36,  7, 18,  4, 20, 48])

In [32]:
np.percentile(a,0)

1.0

In [33]:
np.percentile(a,25)

15.75

In [34]:
np.percentile(a,50)

26.0

In [35]:
np.percentile(a,75)

39.0

In [36]:
np.percentile(a,25)

15.75

In [37]:
IQR = np.percentile(a,75) - np.percentile(a,25)

In [38]:
IQR

23.25

In [39]:
50+24.65+24.65

99.30000000000001

# 파이썬 라이브러리를 이용한 분산, 표준편차 , 범위, 사분위수, IQR 구하기

In [46]:
import numpy as np
from statistics import variance, stdev

np.random.seed(0)

points = np.random.randint(0,100,200)
var = variance(points) ; print("분산: ", var)
std = stdev(points); print("표준편차: ", np.round(std,2))
Range = np.max(points) - np.min(points) ; print("범위: ", range(Range))
print('사분위수 : ')
for val in [0,25,50,75,100]:
    quantile = np.percentile(points, val)
    print("{}% => {}".format(val, quantile))

        
q1, q3 = np.percentile(points, [25,75])
print("IQR: ", q3 - q1)

분산:  821
표준편차:  28.65
범위:  range(0, 99)
사분위수 : 
0% => 0.0
25% => 24.0
50% => 48.0
75% => 72.25
100% => 99.0
IQR:  48.25


In [47]:
from scipy import stats
x_bar , mu, sigma, n = 196, 200, 5.3 , 20

t_sample = (x_bar-mu) / (sigma/np.sqrt(float(n)))
print("검정통게량 = ", np.round(t_sample, 2))

검정통게량 =  -3.38


In [50]:
alpha = 0.05
t_alpha = stats.t.ppf(alpha, n-1) # n-1은 자유도
print('t-table로 부터 임계값 =', np.round(t_alpha,3))

t-table로 부터 임계값 = -1.729


In [49]:
p_val = stats.t.sf(np.abs(t_sample),n-1)
print('t-table의 아랫쪽 꼬리값 p 값 = ', np.round(p_val, 4))

t-table의 아랫쪽 꼬리값 p 값 =  0.0016


In [51]:
x_bar , mu, sigma = 75,56,13.6

z = (x_bar - mu) / sigma
print("z-score : ", np.round(z,2))

p_val = 1 - stats.norm.cdf(z)
print("학생이 {}점 이상 받을 확률 : {}".format(x_bar, np.round(p_val * 100, 2)))

z-score :  1.4
학생이 75점 이상 받을 확률 : 8.12
